### ISSUE TITLE
docker-compose recipe: Fresh instance shows blank white page

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#132]
Full log from docker-compose build && up: http://www.onerussian.com/tmp/docker-compose-dandiarchive-1040994.log

girder is up and accessible (on http://localhost:8091/), but for http://localhost:8092/ browser shows a blank page and console has 
```
DataDetails.vue:72 Uncaught TypeError: Cannot read property 'methods' of undefined
    at Module../node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/@girder/components/src/components/DataDetails.vue?vue&type=script&lang=js& (DataDetails.vue:72)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/@girder/components/src/components/DataDetails.vue?vue&type=script&lang=js& (DataDetails.vue?5690:1)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/@girder/components/src/components/DataDetails.vue (DataDetails.vue:1)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=js& (DandiMetaViewer.vue:233)
vue.runtime.esm.js:8423 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.runtime.esm.js:8434 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

Browser: Chromium Version 79.0.3945.130 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)

**Comment by satra** [comment]
just an fyi that i cannot replicate this bug on osx catalina with current master.

**Comment by yarikoptic** [comment]
Tried again after pulling all relevant base images.  Full log: http://www.onerussian.com/tmp/docker-compose-2-1040994.log -- result is exactly the same.  @satra -- what versions of the base images you have?  here is my list including those built ones:
```
$> docker images | grep -e '^dandi' -e '^node' -e '^girder' -e '^node'
dandi_girder                            latest              44d00353655e        20 minutes ago      1.41GB
dandi_client                            latest              9288faa94496        37 hours ago        143MB
dandi_provision                         latest              04dcbd13b01d        5 days ago          930MB
node                                    latest              7aef30ae6655        6 days ago          943MB
girder/girder                           latest-py3          6c89826e4cf8        6 days ago          1.27GB
node                                    <none>              e0e011be5f0f        2 weeks ago         942MB
girder/girder                           <none>              90b29e2af6ac        3 weeks ago         1.29GB
girder_girder                           latest              429574d14760        5 weeks ago         1.26GB
dandiarchive/pynwb-mpi                  latest              d05cd3020d35        4 months ago        467MB
node                                    8-stretch           52a261fa5e4b        4 months ago        895MB
```

**Comment by yarikoptic** [comment]
Found that my repo is "dirty", so I wonder if `web/package-lock.json` can somehow be implicated
<details>
<summary>my "dirty" state</summary> 

```shell
(git)lena:~/proj/dandi/dandiarchive[master]
$> git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	venvs/
	web/package-lock.json

nothing added to commit but untracked files present (use "git add" to track)
1 36468.....................................:Thu 12 Mar 2020 12:04:02 PM EDT:.
(git)lena:~/proj/dandi/dandiarchive[master]
$> cat web/package-lock.json
{
  "name": "dandi",
  "version": "0.1.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "yarn": {
      "version": "1.19.0",
      "resolved": "https://registry.npmjs.org/yarn/-/yarn-1.19.0.tgz",
      "integrity": "sha512-QLiMoj+ZHo2kT17x1t7erO6gzR+9xSa5z7Lmei1qYM1Sj37wiIFv67kQcH+nkshsO0f03ImXClfkEKUgnsMreQ=="
    }
  }
}

```
</details>
will rebuild after removing it

**Comment by yarikoptic** [comment]
FWIW -- that wasn't it... BTW -- runs fine on another host of mine, so it is something about the state of my laptop which "broke" it (since it was working before), some cache/memory of glorious days somewhere.

**Comment by yarikoptic** [comment]
FWIW, here is the JS where it is happening:
![DeepinScreenshot_select-area_20200312175454](https://user-images.githubusercontent.com/39889/76570042-dcbf2400-648a-11ea-9be7-018da0eb4dcd.png)

so it is `dateFormatter` which is undefined. may be that rings some bell @mgrauer @AlmightyYakob ?

**Comment by yarikoptic** [comment]
Ha -- comparing the logs (should have just grepped ;)) between good (left) and bad (right) builds saw:

![DeepinScreenshot_select-area_20200312180856](https://user-images.githubusercontent.com/39889/76570863-9f5b9600-648c-11ea-9543-452b4e0d4197.png)

which is in text:
```
^[[0m WARNING  Compiled with 4 warnings4:42:58 PM

 warning  in ./src/views/Home.vue?vue&type=script&lang=js&

"export 'DataDetails' (imported as 'GirderDataDetails') was not found in '@girder/components/src/components'
^[[91m<s> [webpack.Progress] 100%

^[[0m
 warning  in ./node_modules/@girder/components/src/components/DataDetails.vue?vue&type=script&lang=js&

"export 'dateFormatter' was not found in '../utils/mixins'

 warning  in ./node_modules/@girder/components/src/components/DataDetails.vue?vue&type=script&lang=js&

"export 'dateFormatter' was not found in '../utils/mixins'

 warning  in ./node_modules/@girder/components/src/components/DataDetails.vue?vue&type=script&lang=js&

"export 'usernameFormatter' was not found in '../utils/mixins'

  File           Size                          Gzipped

  dist/app.js    7012.65 KiB                   1003.82 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

I think the build should treat such "warnings" as "errors" and fail.  Now to look WTF happened which could have lead to it

**Comment by yarikoptic** [comment]
I can only suspect `vue-cli-service build --mode docker` ATM somehow.  Paths listed in the progress log seems to not necessarily be in the same order, and I suspect that in the "bad" run (where it reports built 1308) it just manages to miss some (in the good one it is 1314).

**Comment by yarikoptic** [comment]
ok, giving up for now -- all what I have tried is provided in https://github.com/dandi/dandiarchive/pull/135 .  Someone who has a clue in those technologies should make build robust, and not fail on random super-fast laptops ;)

**Comment by danlamanna** [comment]
FWIW I wasn't able to reproduce this either.

**Comment by yarikoptic** [comment]
I am ok to be "unique" ;-)  I know that it makes it harder to fix, but if you have ideas on how to e.g. disable parallel builds like I tried to do in #135 (but without notable effect -- may be I did it wrong) -- I could try on my unique speedy laptop ;)

**Comment by brianhelba** [comment]
@yarikoptic Are you able to reproduce this if you build from the `refactor` branch? That has updated a bunch of libraries from the build process.

**Comment by mgrauer** [comment]
Fixed

**Comment by yarikoptic** [comment]
Sorry, missed original request, but the issue persists although differently. Just did a fresh 
```
docker-compose build --pull
docker-compose up
```
in
```
(git)lena:~/proj/dandi/dandiarchive[master]docker
$> git describe
fatal: No annotated tags can describe 'd30abc143a776e22de8ff1814c3da4e98b32f918'.
However, there were unannotated tags: try --tags.
```
and get a blank page with console saying
```
rest.js:37 Uncaught TypeError: Cannot read property 'endsWith' of undefined
    at eval (rest.js:37)
    at Module../src/rest.js (app.js:1365)
    at __webpack_require__ (app.js:80)
    at eval (AppBar.vue?./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options:4)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/AppBar/AppBar.vue?vue&type=script&lang=js& (app.js:190)
    at __webpack_require__ (app.js:80)
    at eval (VM2345 AppBar.vue:2)
    at Module../src/components/AppBar/AppBar.vue?vue&type=script&lang=js& (app.js:1101)
    at __webpack_require__ (app.js:80)
    at eval (VM2345 AppBar.vue:3)
```

**Comment by yarikoptic** [comment]
@mgrauer could someone look into it?  issue persists, might relate to the port number change etc.

**Comment by mgrauer** [comment]
I don't think this fits the definition of critical. We are trying to focus on the API unification currently.

@danlamanna looked into it before and couldn't reproduce, @satra also tried to replicate and couldn't.

**Comment by yarikoptic** [comment]
I guess I have rushed to re-open instead of just filing a new issue.  I would appreciate if `docker-compose up` + visit frontpage would have been tried again -- original issue from March was likely a different one and this one I believe is appearing ATM for both me and @jwodder .  Meanwhile I have reproduced it again on this master as of  0.1.0-18-g6fcf80c

- I removed all docker containers (`docker ps -a | f1 | grep -v CON | xargs docker rm`)
- pruned all volumes (`docker volume prune`)
- `cd docker`
- `docker-compose up` and waited for provisioning to stop with `docker_provision_1 exited with code 0`
- went to http://localhost:8085/ -- saw blank page.

<details>
<summary>inspect, console showed that traceback</summary> 

```
Uncaught TypeError: Cannot read property 'endsWith' of undefined
    at eval (rest.js:37)
    at Module../src/rest.js (app.js:1365)
    at __webpack_require__ (app.js:80)
    at eval (AppBar.vue?./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options:4)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/AppBar/AppBar.vue?vue&type=script&lang=js& (app.js:190)
    at __webpack_require__ (app.js:80)
    at eval (VM1161 AppBar.vue:2)
    at Module../src/components/AppBar/AppBar.vue?vue&type=script&lang=js& (app.js:1101)
    at __webpack_require__ (app.js:80)
    at eval (VM1161 AppBar.vue:3)
```
</details>
and looking at that long onelined js smells like `VUE_APP_PUBLISH_API_ROOT` is not setup/passed correctly...

**Comment by yarikoptic** [comment]
oh, I wonder if that is just due to the manifestation of https://github.com/dandi/dandiarchive/issues/474 and what @jwodder ran into awhile back...?

**Comment by waxlamp** [comment]
Closing because the new API provides a Docker compose setup that works for John and Yarik.
