### ISSUE TITLE
Do not hardcode "dandiarchive.org"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#140]
I am working a local instance and registered a new dandiset.  Upon visiting that dandiset metadata record I see a URL which directs to dandiarchive.org:
![DeepinScreenshot_select-area_20200313110207](https://user-images.githubusercontent.com/39889/76632785-1be88600-651a-11ea-868a-02836eeebc28.png)

Ideally it should have been `https://localhost:8092/dandiset/000000/draft` in my case and worked (it doesn't ATM (separate issue #139)

**Comment by satra** [comment]
the permalink url should indeed be `dandiarchive.org` , which is the redirector, rather than localhost:8092. this allows us to change any of the services behind the links without changing the URL.

however, for development since we set a vue development mode flag, we could use that to change the permalink URL for development.

**Comment by yarikoptic** [comment]
Agree but - permalink should be dandiarchive.org **only** for the central deployment, we do not expect independent deployments to point to dandiarchive.org, correct? So any other deployment (e.g. via docker-compose) should have that configured (via the means you mentioned) or default to show server:port for where redirector running in that (e.g. development) case.

**Comment by yarikoptic** [comment]
FWIW and FTR an updated use-case -- staging web ui with staging api server (so dandisets have no correspondence with production server(s)) points to main redirector: 
![image](https://user-images.githubusercontent.com/39889/128234739-5505b0ca-e586-4e46-8842-569bce620564.png)

redirector url should be a part of the deployment configuration.  If not provided (e.g. if we don't have staging redirector instance) -- should probably just show the URL for the dandiset landing page on that web UI instance.

**Comment by djarecka** [comment]
I think this is already fixed. Please reopen if there is still anything to do with it

**Comment by waxlamp** [comment]
I don't think it's fixed. Go to the staging instance, open a dandiset, and click on the "download" dropdown, and scroll down to see a dandiarchive.org URL in the download instructions.
